/**
 * generated by Xtext 2.10.0
 */
package org.xtext.geotweet.gtdsl.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;
import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor;
import org.xtext.geotweet.gtdsl.ui.AbstractGTDslUiModule;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
@FinalFieldsConstructor
@SuppressWarnings("all")
public class GTDslUiModule extends AbstractGTDslUiModule {
  public GTDslUiModule(final AbstractUIPlugin plugin) {
    super(plugin);
  }
}
