/*
 * generated by Xtext 2.10.0
 */
package org.xtext.geotweet.gtdsl.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractGTDslScopeProvider extends DelegatingScopeProvider {
}
