/**
 * generated by Xtext 2.10.0
 */
package org.xtext.geotweet.gtdsl.gTDsl.impl;

import java.util.Collection;

import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.util.EObjectContainmentEList;
import org.eclipse.emf.ecore.util.InternalEList;

import org.xtext.geotweet.gtdsl.gTDsl.Country;
import org.xtext.geotweet.gtdsl.gTDsl.CountryList;
import org.xtext.geotweet.gtdsl.gTDsl.GTDslPackage;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Country List</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.geotweet.gtdsl.gTDsl.impl.CountryListImpl#getCountry <em>Country</em>}</li>
 * </ul>
 *
 * @generated
 */
public class CountryListImpl extends TypeImpl implements CountryList
{
  /**
   * The cached value of the '{@link #getCountry() <em>Country</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getCountry()
   * @generated
   * @ordered
   */
  protected EList<Country> country;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected CountryListImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return GTDslPackage.Literals.COUNTRY_LIST;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EList<Country> getCountry()
  {
    if (country == null)
    {
      country = new EObjectContainmentEList<Country>(Country.class, this, GTDslPackage.COUNTRY_LIST__COUNTRY);
    }
    return country;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case GTDslPackage.COUNTRY_LIST__COUNTRY:
        return ((InternalEList<?>)getCountry()).basicRemove(otherEnd, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case GTDslPackage.COUNTRY_LIST__COUNTRY:
        return getCountry();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @SuppressWarnings("unchecked")
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case GTDslPackage.COUNTRY_LIST__COUNTRY:
        getCountry().clear();
        getCountry().addAll((Collection<? extends Country>)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case GTDslPackage.COUNTRY_LIST__COUNTRY:
        getCountry().clear();
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case GTDslPackage.COUNTRY_LIST__COUNTRY:
        return country != null && !country.isEmpty();
    }
    return super.eIsSet(featureID);
  }

} //CountryListImpl
