/**
 * generated by Xtext 2.10.0
 */
package org.xtext.geotweet.gtdsl.gTDsl.impl;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.emf.ecore.EPackage;

import org.eclipse.emf.ecore.impl.EFactoryImpl;

import org.eclipse.emf.ecore.plugin.EcorePlugin;

import org.xtext.geotweet.gtdsl.gTDsl.*;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model <b>Factory</b>.
 * <!-- end-user-doc -->
 * @generated
 */
public class GTDslFactoryImpl extends EFactoryImpl implements GTDslFactory
{
  /**
   * Creates the default factory implementation.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public static GTDslFactory init()
  {
    try
    {
      GTDslFactory theGTDslFactory = (GTDslFactory)EPackage.Registry.INSTANCE.getEFactory(GTDslPackage.eNS_URI);
      if (theGTDslFactory != null)
      {
        return theGTDslFactory;
      }
    }
    catch (Exception exception)
    {
      EcorePlugin.INSTANCE.log(exception);
    }
    return new GTDslFactoryImpl();
  }

  /**
   * Creates an instance of the factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public GTDslFactoryImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EObject create(EClass eClass)
  {
    switch (eClass.getClassifierID())
    {
      case GTDslPackage.MODEL: return createModel();
      case GTDslPackage.TYPE: return createType();
      case GTDslPackage.HASHTAG: return createHashtag();
      case GTDslPackage.HASHTAG_LIST: return createHashtagList();
      case GTDslPackage.COUNTRY: return createCountry();
      case GTDslPackage.COUNTRY_LIST: return createCountryList();
      default:
        throw new IllegalArgumentException("The class '" + eClass.getName() + "' is not a valid classifier");
    }
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public Model createModel()
  {
    ModelImpl model = new ModelImpl();
    return model;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public Type createType()
  {
    TypeImpl type = new TypeImpl();
    return type;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public Hashtag createHashtag()
  {
    HashtagImpl hashtag = new HashtagImpl();
    return hashtag;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public HashtagList createHashtagList()
  {
    HashtagListImpl hashtagList = new HashtagListImpl();
    return hashtagList;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public Country createCountry()
  {
    CountryImpl country = new CountryImpl();
    return country;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public CountryList createCountryList()
  {
    CountryListImpl countryList = new CountryListImpl();
    return countryList;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public GTDslPackage getGTDslPackage()
  {
    return (GTDslPackage)getEPackage();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @deprecated
   * @generated
   */
  @Deprecated
  public static GTDslPackage getPackage()
  {
    return GTDslPackage.eINSTANCE;
  }

} //GTDslFactoryImpl
