/**
 * generated by Xtext 2.10.0
 */
package org.xtext.geotweet.gtdsl.gTDsl.impl;

import java.util.Collection;

import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.util.EObjectContainmentEList;
import org.eclipse.emf.ecore.util.InternalEList;

import org.xtext.geotweet.gtdsl.gTDsl.GTDslPackage;
import org.xtext.geotweet.gtdsl.gTDsl.Hashtag;
import org.xtext.geotweet.gtdsl.gTDsl.HashtagList;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Hashtag List</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.geotweet.gtdsl.gTDsl.impl.HashtagListImpl#getHashtag <em>Hashtag</em>}</li>
 * </ul>
 *
 * @generated
 */
public class HashtagListImpl extends TypeImpl implements HashtagList
{
  /**
   * The cached value of the '{@link #getHashtag() <em>Hashtag</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getHashtag()
   * @generated
   * @ordered
   */
  protected EList<Hashtag> hashtag;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected HashtagListImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return GTDslPackage.Literals.HASHTAG_LIST;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EList<Hashtag> getHashtag()
  {
    if (hashtag == null)
    {
      hashtag = new EObjectContainmentEList<Hashtag>(Hashtag.class, this, GTDslPackage.HASHTAG_LIST__HASHTAG);
    }
    return hashtag;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case GTDslPackage.HASHTAG_LIST__HASHTAG:
        return ((InternalEList<?>)getHashtag()).basicRemove(otherEnd, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case GTDslPackage.HASHTAG_LIST__HASHTAG:
        return getHashtag();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @SuppressWarnings("unchecked")
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case GTDslPackage.HASHTAG_LIST__HASHTAG:
        getHashtag().clear();
        getHashtag().addAll((Collection<? extends Hashtag>)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case GTDslPackage.HASHTAG_LIST__HASHTAG:
        getHashtag().clear();
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case GTDslPackage.HASHTAG_LIST__HASHTAG:
        return hashtag != null && !hashtag.isEmpty();
    }
    return super.eIsSet(featureID);
  }

} //HashtagListImpl
