/**
 * generated by Xtext 2.10.0
 */
package org.xtext.geotweet.gtdsl;

import org.xtext.geotweet.gtdsl.AbstractGTDslRuntimeModule;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
@SuppressWarnings("all")
public class GTDslRuntimeModule extends AbstractGTDslRuntimeModule {
}
