/**
 * generated by Xtext 2.10.0
 */
package org.xtext.geotweet.gtdsl;

import org.xtext.geotweet.gtdsl.GTDslStandaloneSetupGenerated;

/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
@SuppressWarnings("all")
public class GTDslStandaloneSetup extends GTDslStandaloneSetupGenerated {
  public static void doSetup() {
    GTDslStandaloneSetup _gTDslStandaloneSetup = new GTDslStandaloneSetup();
    _gTDslStandaloneSetup.createInjectorAndDoEMFRegistration();
  }
}
