/**
 * generated by Xtext 2.10.0
 */
package org.xtext.geotweet.gtdsl.gTDsl;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see org.xtext.geotweet.gtdsl.gTDsl.GTDslFactory
 * @model kind="package"
 * @generated
 */
public interface GTDslPackage extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "gTDsl";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "http://www.xtext.org/geotweet/gtdsl/GTDsl";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "gTDsl";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  GTDslPackage eINSTANCE = org.xtext.geotweet.gtdsl.gTDsl.impl.GTDslPackageImpl.init();

  /**
   * The meta object id for the '{@link org.xtext.geotweet.gtdsl.gTDsl.impl.ModelImpl <em>Model</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.geotweet.gtdsl.gTDsl.impl.ModelImpl
   * @see org.xtext.geotweet.gtdsl.gTDsl.impl.GTDslPackageImpl#getModel()
   * @generated
   */
  int MODEL = 0;

  /**
   * The feature id for the '<em><b>Elements</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MODEL__ELEMENTS = 0;

  /**
   * The feature id for the '<em><b>Query</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MODEL__QUERY = 1;

  /**
   * The number of structural features of the '<em>Model</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MODEL_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link org.xtext.geotweet.gtdsl.gTDsl.impl.TypeImpl <em>Type</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.geotweet.gtdsl.gTDsl.impl.TypeImpl
   * @see org.xtext.geotweet.gtdsl.gTDsl.impl.GTDslPackageImpl#getType()
   * @generated
   */
  int TYPE = 1;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TYPE__NAME = 0;

  /**
   * The number of structural features of the '<em>Type</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TYPE_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.geotweet.gtdsl.gTDsl.impl.HashtagImpl <em>Hashtag</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.geotweet.gtdsl.gTDsl.impl.HashtagImpl
   * @see org.xtext.geotweet.gtdsl.gTDsl.impl.GTDslPackageImpl#getHashtag()
   * @generated
   */
  int HASHTAG = 2;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int HASHTAG__NAME = 0;

  /**
   * The feature id for the '<em><b>Color</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int HASHTAG__COLOR = 1;

  /**
   * The number of structural features of the '<em>Hashtag</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int HASHTAG_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link org.xtext.geotweet.gtdsl.gTDsl.impl.HashtagListImpl <em>Hashtag List</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.geotweet.gtdsl.gTDsl.impl.HashtagListImpl
   * @see org.xtext.geotweet.gtdsl.gTDsl.impl.GTDslPackageImpl#getHashtagList()
   * @generated
   */
  int HASHTAG_LIST = 3;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int HASHTAG_LIST__NAME = TYPE__NAME;

  /**
   * The feature id for the '<em><b>Hashtag</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int HASHTAG_LIST__HASHTAG = TYPE_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Hashtag List</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int HASHTAG_LIST_FEATURE_COUNT = TYPE_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link org.xtext.geotweet.gtdsl.gTDsl.impl.CountryImpl <em>Country</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.geotweet.gtdsl.gTDsl.impl.CountryImpl
   * @see org.xtext.geotweet.gtdsl.gTDsl.impl.GTDslPackageImpl#getCountry()
   * @generated
   */
  int COUNTRY = 4;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COUNTRY__NAME = 0;

  /**
   * The number of structural features of the '<em>Country</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COUNTRY_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.geotweet.gtdsl.gTDsl.impl.CountryListImpl <em>Country List</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.geotweet.gtdsl.gTDsl.impl.CountryListImpl
   * @see org.xtext.geotweet.gtdsl.gTDsl.impl.GTDslPackageImpl#getCountryList()
   * @generated
   */
  int COUNTRY_LIST = 5;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COUNTRY_LIST__NAME = TYPE__NAME;

  /**
   * The feature id for the '<em><b>Country</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COUNTRY_LIST__COUNTRY = TYPE_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Country List</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COUNTRY_LIST_FEATURE_COUNT = TYPE_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link org.xtext.geotweet.gtdsl.gTDsl.impl.QueryImpl <em>Query</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.geotweet.gtdsl.gTDsl.impl.QueryImpl
   * @see org.xtext.geotweet.gtdsl.gTDsl.impl.GTDslPackageImpl#getQuery()
   * @generated
   */
  int QUERY = 6;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int QUERY__NAME = 0;

  /**
   * The feature id for the '<em><b>Hashtags</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int QUERY__HASHTAGS = 1;

  /**
   * The feature id for the '<em><b>Countries</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int QUERY__COUNTRIES = 2;

  /**
   * The number of structural features of the '<em>Query</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int QUERY_FEATURE_COUNT = 3;


  /**
   * Returns the meta object for class '{@link org.xtext.geotweet.gtdsl.gTDsl.Model <em>Model</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Model</em>'.
   * @see org.xtext.geotweet.gtdsl.gTDsl.Model
   * @generated
   */
  EClass getModel();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.geotweet.gtdsl.gTDsl.Model#getElements <em>Elements</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Elements</em>'.
   * @see org.xtext.geotweet.gtdsl.gTDsl.Model#getElements()
   * @see #getModel()
   * @generated
   */
  EReference getModel_Elements();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.geotweet.gtdsl.gTDsl.Model#getQuery <em>Query</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Query</em>'.
   * @see org.xtext.geotweet.gtdsl.gTDsl.Model#getQuery()
   * @see #getModel()
   * @generated
   */
  EReference getModel_Query();

  /**
   * Returns the meta object for class '{@link org.xtext.geotweet.gtdsl.gTDsl.Type <em>Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Type</em>'.
   * @see org.xtext.geotweet.gtdsl.gTDsl.Type
   * @generated
   */
  EClass getType();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.geotweet.gtdsl.gTDsl.Type#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.xtext.geotweet.gtdsl.gTDsl.Type#getName()
   * @see #getType()
   * @generated
   */
  EAttribute getType_Name();

  /**
   * Returns the meta object for class '{@link org.xtext.geotweet.gtdsl.gTDsl.Hashtag <em>Hashtag</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Hashtag</em>'.
   * @see org.xtext.geotweet.gtdsl.gTDsl.Hashtag
   * @generated
   */
  EClass getHashtag();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.geotweet.gtdsl.gTDsl.Hashtag#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.xtext.geotweet.gtdsl.gTDsl.Hashtag#getName()
   * @see #getHashtag()
   * @generated
   */
  EAttribute getHashtag_Name();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.geotweet.gtdsl.gTDsl.Hashtag#getColor <em>Color</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Color</em>'.
   * @see org.xtext.geotweet.gtdsl.gTDsl.Hashtag#getColor()
   * @see #getHashtag()
   * @generated
   */
  EAttribute getHashtag_Color();

  /**
   * Returns the meta object for class '{@link org.xtext.geotweet.gtdsl.gTDsl.HashtagList <em>Hashtag List</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Hashtag List</em>'.
   * @see org.xtext.geotweet.gtdsl.gTDsl.HashtagList
   * @generated
   */
  EClass getHashtagList();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.geotweet.gtdsl.gTDsl.HashtagList#getHashtag <em>Hashtag</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Hashtag</em>'.
   * @see org.xtext.geotweet.gtdsl.gTDsl.HashtagList#getHashtag()
   * @see #getHashtagList()
   * @generated
   */
  EReference getHashtagList_Hashtag();

  /**
   * Returns the meta object for class '{@link org.xtext.geotweet.gtdsl.gTDsl.Country <em>Country</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Country</em>'.
   * @see org.xtext.geotweet.gtdsl.gTDsl.Country
   * @generated
   */
  EClass getCountry();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.geotweet.gtdsl.gTDsl.Country#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.xtext.geotweet.gtdsl.gTDsl.Country#getName()
   * @see #getCountry()
   * @generated
   */
  EAttribute getCountry_Name();

  /**
   * Returns the meta object for class '{@link org.xtext.geotweet.gtdsl.gTDsl.CountryList <em>Country List</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Country List</em>'.
   * @see org.xtext.geotweet.gtdsl.gTDsl.CountryList
   * @generated
   */
  EClass getCountryList();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.geotweet.gtdsl.gTDsl.CountryList#getCountry <em>Country</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Country</em>'.
   * @see org.xtext.geotweet.gtdsl.gTDsl.CountryList#getCountry()
   * @see #getCountryList()
   * @generated
   */
  EReference getCountryList_Country();

  /**
   * Returns the meta object for class '{@link org.xtext.geotweet.gtdsl.gTDsl.Query <em>Query</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Query</em>'.
   * @see org.xtext.geotweet.gtdsl.gTDsl.Query
   * @generated
   */
  EClass getQuery();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.geotweet.gtdsl.gTDsl.Query#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.xtext.geotweet.gtdsl.gTDsl.Query#getName()
   * @see #getQuery()
   * @generated
   */
  EAttribute getQuery_Name();

  /**
   * Returns the meta object for the reference '{@link org.xtext.geotweet.gtdsl.gTDsl.Query#getHashtags <em>Hashtags</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Hashtags</em>'.
   * @see org.xtext.geotweet.gtdsl.gTDsl.Query#getHashtags()
   * @see #getQuery()
   * @generated
   */
  EReference getQuery_Hashtags();

  /**
   * Returns the meta object for the reference '{@link org.xtext.geotweet.gtdsl.gTDsl.Query#getCountries <em>Countries</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Countries</em>'.
   * @see org.xtext.geotweet.gtdsl.gTDsl.Query#getCountries()
   * @see #getQuery()
   * @generated
   */
  EReference getQuery_Countries();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  GTDslFactory getGTDslFactory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link org.xtext.geotweet.gtdsl.gTDsl.impl.ModelImpl <em>Model</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.geotweet.gtdsl.gTDsl.impl.ModelImpl
     * @see org.xtext.geotweet.gtdsl.gTDsl.impl.GTDslPackageImpl#getModel()
     * @generated
     */
    EClass MODEL = eINSTANCE.getModel();

    /**
     * The meta object literal for the '<em><b>Elements</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference MODEL__ELEMENTS = eINSTANCE.getModel_Elements();

    /**
     * The meta object literal for the '<em><b>Query</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference MODEL__QUERY = eINSTANCE.getModel_Query();

    /**
     * The meta object literal for the '{@link org.xtext.geotweet.gtdsl.gTDsl.impl.TypeImpl <em>Type</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.geotweet.gtdsl.gTDsl.impl.TypeImpl
     * @see org.xtext.geotweet.gtdsl.gTDsl.impl.GTDslPackageImpl#getType()
     * @generated
     */
    EClass TYPE = eINSTANCE.getType();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute TYPE__NAME = eINSTANCE.getType_Name();

    /**
     * The meta object literal for the '{@link org.xtext.geotweet.gtdsl.gTDsl.impl.HashtagImpl <em>Hashtag</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.geotweet.gtdsl.gTDsl.impl.HashtagImpl
     * @see org.xtext.geotweet.gtdsl.gTDsl.impl.GTDslPackageImpl#getHashtag()
     * @generated
     */
    EClass HASHTAG = eINSTANCE.getHashtag();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute HASHTAG__NAME = eINSTANCE.getHashtag_Name();

    /**
     * The meta object literal for the '<em><b>Color</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute HASHTAG__COLOR = eINSTANCE.getHashtag_Color();

    /**
     * The meta object literal for the '{@link org.xtext.geotweet.gtdsl.gTDsl.impl.HashtagListImpl <em>Hashtag List</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.geotweet.gtdsl.gTDsl.impl.HashtagListImpl
     * @see org.xtext.geotweet.gtdsl.gTDsl.impl.GTDslPackageImpl#getHashtagList()
     * @generated
     */
    EClass HASHTAG_LIST = eINSTANCE.getHashtagList();

    /**
     * The meta object literal for the '<em><b>Hashtag</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference HASHTAG_LIST__HASHTAG = eINSTANCE.getHashtagList_Hashtag();

    /**
     * The meta object literal for the '{@link org.xtext.geotweet.gtdsl.gTDsl.impl.CountryImpl <em>Country</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.geotweet.gtdsl.gTDsl.impl.CountryImpl
     * @see org.xtext.geotweet.gtdsl.gTDsl.impl.GTDslPackageImpl#getCountry()
     * @generated
     */
    EClass COUNTRY = eINSTANCE.getCountry();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute COUNTRY__NAME = eINSTANCE.getCountry_Name();

    /**
     * The meta object literal for the '{@link org.xtext.geotweet.gtdsl.gTDsl.impl.CountryListImpl <em>Country List</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.geotweet.gtdsl.gTDsl.impl.CountryListImpl
     * @see org.xtext.geotweet.gtdsl.gTDsl.impl.GTDslPackageImpl#getCountryList()
     * @generated
     */
    EClass COUNTRY_LIST = eINSTANCE.getCountryList();

    /**
     * The meta object literal for the '<em><b>Country</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference COUNTRY_LIST__COUNTRY = eINSTANCE.getCountryList_Country();

    /**
     * The meta object literal for the '{@link org.xtext.geotweet.gtdsl.gTDsl.impl.QueryImpl <em>Query</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.geotweet.gtdsl.gTDsl.impl.QueryImpl
     * @see org.xtext.geotweet.gtdsl.gTDsl.impl.GTDslPackageImpl#getQuery()
     * @generated
     */
    EClass QUERY = eINSTANCE.getQuery();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute QUERY__NAME = eINSTANCE.getQuery_Name();

    /**
     * The meta object literal for the '<em><b>Hashtags</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference QUERY__HASHTAGS = eINSTANCE.getQuery_Hashtags();

    /**
     * The meta object literal for the '<em><b>Countries</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference QUERY__COUNTRIES = eINSTANCE.getQuery_Countries();

  }

} //GTDslPackage
