/**
 * generated by Xtext 2.10.0
 */
package org.xtext.geotweet.gtdsl.gTDsl;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Hashtag List</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.geotweet.gtdsl.gTDsl.HashtagList#getHashtag <em>Hashtag</em>}</li>
 * </ul>
 *
 * @see org.xtext.geotweet.gtdsl.gTDsl.GTDslPackage#getHashtagList()
 * @model
 * @generated
 */
public interface HashtagList extends Type
{
  /**
   * Returns the value of the '<em><b>Hashtag</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.geotweet.gtdsl.gTDsl.Hashtag}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Hashtag</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Hashtag</em>' containment reference list.
   * @see org.xtext.geotweet.gtdsl.gTDsl.GTDslPackage#getHashtagList_Hashtag()
   * @model containment="true"
   * @generated
   */
  EList<Hashtag> getHashtag();

} // HashtagList
