/**
 * generated by Xtext 2.10.0
 */
package org.xtext.geotweet.gtdsl.gTDsl;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Query</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.geotweet.gtdsl.gTDsl.Query#getName <em>Name</em>}</li>
 *   <li>{@link org.xtext.geotweet.gtdsl.gTDsl.Query#getHashtags <em>Hashtags</em>}</li>
 *   <li>{@link org.xtext.geotweet.gtdsl.gTDsl.Query#getCountries <em>Countries</em>}</li>
 * </ul>
 *
 * @see org.xtext.geotweet.gtdsl.gTDsl.GTDslPackage#getQuery()
 * @model
 * @generated
 */
public interface Query extends EObject
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Name</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see org.xtext.geotweet.gtdsl.gTDsl.GTDslPackage#getQuery_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link org.xtext.geotweet.gtdsl.gTDsl.Query#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Hashtags</b></em>' reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Hashtags</em>' reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Hashtags</em>' reference.
   * @see #setHashtags(HashtagList)
   * @see org.xtext.geotweet.gtdsl.gTDsl.GTDslPackage#getQuery_Hashtags()
   * @model
   * @generated
   */
  HashtagList getHashtags();

  /**
   * Sets the value of the '{@link org.xtext.geotweet.gtdsl.gTDsl.Query#getHashtags <em>Hashtags</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Hashtags</em>' reference.
   * @see #getHashtags()
   * @generated
   */
  void setHashtags(HashtagList value);

  /**
   * Returns the value of the '<em><b>Countries</b></em>' reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Countries</em>' reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Countries</em>' reference.
   * @see #setCountries(CountryList)
   * @see org.xtext.geotweet.gtdsl.gTDsl.GTDslPackage#getQuery_Countries()
   * @model
   * @generated
   */
  CountryList getCountries();

  /**
   * Sets the value of the '{@link org.xtext.geotweet.gtdsl.gTDsl.Query#getCountries <em>Countries</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Countries</em>' reference.
   * @see #getCountries()
   * @generated
   */
  void setCountries(CountryList value);

} // Query
