/*
 * generated by Xtext 2.10.0
 */
package org.xtext.geotweet.gtdsl.ui.tests;

import com.google.inject.Injector;
import org.eclipse.xtext.junit4.IInjectorProvider;
import org.xtext.geotweet.gtdsl.ui.internal.GtdslActivator;

public class GTDslUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return GtdslActivator.getInstance().getInjector("org.xtext.geotweet.gtdsl.GTDsl");
	}

}
