/*
 * generated by Xtext 2.10.0
 */
package org.xtext.geotweet.gtdsl.ui;

import com.google.inject.Injector;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;
import org.xtext.geotweet.gtdsl.ui.internal.GtdslActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class GTDslExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return GtdslActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return GtdslActivator.getInstance().getInjector(GtdslActivator.ORG_XTEXT_GEOTWEET_GTDSL_GTDSL);
	}
	
}
