/**
 * generated by Xtext 2.10.0
 */
package org.xtext.geotweet.gtdsl.validation;

import org.xtext.geotweet.gtdsl.validation.AbstractGTDslValidator;

/**
 * This class contains custom validation rules.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
@SuppressWarnings("all")
public class GTDslValidator extends AbstractGTDslValidator {
}
