/**
 * generated by Xtext 2.10.0
 */
package org.xtext.geotweet.gtdsl.scoping;

import org.xtext.geotweet.gtdsl.scoping.AbstractGTDslScopeProvider;

/**
 * This class contains custom scoping description.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#scoping
 * on how and when to use it.
 */
@SuppressWarnings("all")
public class GTDslScopeProvider extends AbstractGTDslScopeProvider {
}
